name: Build macOS

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: brew install cmake ninja curl nlohmann-json qt@6

      - name: Configure and Build
        run: |
          export CMAKE_PREFIX_PATH=$(brew --prefix qt@6)
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: flood_monitor-macos
          path: build/flood_monitor