name: Build Windows

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.0'
          modules: 'qtpositioning'

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install curl nlohmann-json --triplet=x64-windows

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: flood_monitor-windows
          path: build/Release/flood_monitor.exe